name: Output information
on:
 issues:
    types: [opened, edited, milestoned]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Detail Issue
        run: echo "${{ toJSON(github.event)}}"